name: Publish to npm
on:
  workflow_call:
    inputs:
      branch:
        description: 'branch'
        required: true
        type: string
        default: master
      version:
        description: 'Version'     
        required: false
        type: string
      git-tag:
        description: 'git tag'
        required: false
        type: string
        default: ''
      npm-tag:
        description: 'npm tag'
        required: false
        type: string
        default: ''
      release-body:
        required: false
        type: string
        default: ''

    secrets:
      NPM_TOKEN:
        required: true

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Determine Version based on input or tag
        id: version
        run: if [ "$VERSION" != "" ]; then echo ::set-output name=version::${VERSION}; else echo ::set-output name=version::${RELEASE_TAG_NAME:1}; fi
        env:
          VERSION: ${{ inputs.version }}
          TAG: ${{ inputs.git-tag }}
      - uses: actions/checkout@v3.0.2
        with:
          fetch-depth: 0
          ref: ${{inputs.branch}}

      - name: Set version in package.json
        run: |
          SEARCH='("version":[[:space:]]*").+(")'
          REPLACE="\1${VERSION}\2"
          sed -i -E "s/${SEARCH}/${REPLACE}/g" package.json
        env:
          VERSION: ${{ steps.version.outputs.version}}

      - name: Update CHANGELOG.md
        if: ${{ inputs.release-body != '' }}
        run: |
          touch CHANGELOG.md
          echo -e "${VERSION} / $(date +%Y-%m-%d)\n==================\n\n$RELEASE_BODY \n\n $(cat CHANGELOG.md)" > CHANGELOG.md
          git add ./CHANGELOG.md
        env:
          RELEASE_BODY: ${{github.event.release.body}}
          VERSION: ${{ steps.version.outputs.version}}

      - name: Commit and Push Changes
        if: ${{ inputs.git-tag != '' }}
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add ./package.json
          git add ./CHANGELOG.md
          git commit -m "Release ${VERSION}"
          git push origin HEAD:${BRANCH}
        env:
          VERSION: ${{ steps.version.outputs.version}}
          BRANCH: ${{inputs.branch}}

      - name: Update tag
        if: ${{ inputs.git-tag }}
        run: git tag -f ${TAG}
        env:
          TAG: ${{inputs.git-tag}}

      - name: Build package
        run: |
          npm i
          npm run build

      - name: Publish on npm
        run: |
          if [ "$NPM_TAG" = "" ]; then npm publish --access public; else --tag $NPM_TAG; fi
        env:
          NPM_TAG: ${{inputs.npm-tag}}
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
          