name: Release
on:
  workflow_call:
    inputs:
      version:
        description: 'Version'
        required: false
        type: string
      branch:
        description: 'branch'
        required: true
        type: string
        default: master
      git-tag:
        description: 'git tag'
        required: false
        type: string
        default: ''

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Determine Version based on input or tag
        id: version
        run: if [ "$VERSION" != "" ]; then echo ::set-output name=version::${VERSION}; else echo ::set-output name=version::${TAG:1}; fi
        env:
          VERSION: ${{ inputs.version }}
          TAG: ${{ inputs.git-tag }}
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{inputs.branch}}

      - name: Set version in package.json
        run: |
          SEARCH='("version":[[:space:]]*").+(")'
          REPLACE="\1${VERSION}\2"
          sed -i -E "s/${SEARCH}/${REPLACE}/g" package.json
        env:
          VERSION: ${{ steps.version.outputs.version}}

      - name: Commit and Push Changes
        if: ${{ inputs.git-tag != '' }}
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add ./package.json
          git commit -m "Release ${VERSION}"
          git push origin HEAD:${BRANCH}
        env:
          VERSION: ${{ steps.version.outputs.version}}
          BRANCH: ${{inputs.branch}}

      - name: Update tag
        if: ${{ inputs.git-tag }}
        run: git tag -f ${TAG}
        env:
          TAG: ${{inputs.git-tag}}
