name: "Handle stale issues and pull-requests"
on:
  workflow_call:
    inputs:
      closeStale:
        description: 'Close stale'     
        required: false
        type: boolean
        default: false
      lockStale:
        description: 'Lock stale'     
        required: false
        type: boolean
        default: false

permissions:
  issues: write
  pull-requests: write

concurrency:
  group: lock

jobs:
  close-stale:
    if: >
      !failure() &&
      !cancelled() &&
      inputs.closeStale == true
    runs-on: ubuntu-latest
    steps:
      - name: stale
        uses: actions/stale@v5.0.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: >
            This issue is stale because it has been open 14 days with no
            activity. Remove stale label or comment or this will be closed in
            7 days
          close-issue-message: >
            This issue was closed because it has been inactive for 21 days since
            being marked as stale.
          days-before-stale: 14
          days-before-close: 7

  lock-stale:
    if: >
      !failure() &&
      !cancelled() &&
      inputs.lockStale == true
    runs-on: ubuntu-latest
    steps:
      - uses: dessant/lock-threads@v3.0.0
        with:
          issue-inactive-days: '90'
          issue-comment: >
            This issue has been automatically locked since there has not been
            any recent activity after it was closed.
            Please open a new issue for related bugs.
          pr-comment: >
            This pull request has been automatically locked since there has not
            been any recent activity after it was closed.
            Please open a new issue for related bugs.
